In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
X = iris.data
y = iris.target

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn = KNeighborsClassifier(n_neighbors=1)

In [8]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [9]:
knn.predict([[3,5,4,2]])

array([2])

In [10]:
print("Predicted target name:", iris['target_names'][knn.predict([[3, 5, 4, 2]])])

Predicted target name: ['virginica']


In [11]:
X_new = np.array([[2,5,3,4]])
print("X_new.shape:", X_new.shape)

X_new.shape: (1, 4)


In [12]:
my_predict = knn.predict(X_new)

In [13]:
print("Prediction:", my_predict)

Prediction: [2]


In [15]:
print("Predicted target name:", iris['target_names'][my_predict])

Predicted target name: ['virginica']


In [16]:
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

In [17]:
knn = KNeighborsClassifier(n_neighbors=3)

In [18]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [19]:
knn.predict(X_new)

array([1, 1])

In [24]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X, y)
lr.predict(X_new)

c:\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


array([2, 0])

In [25]:
import sklearn

In [26]:
sklearn.__version__

'0.20.3'