In [1]:
import numpy as np

In [3]:
X, y = np.arange(10).reshape((5,2)), range(5)

In [4]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
y

range(0, 5)

In [6]:
list(y)

[0, 1, 2, 3, 4]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 4)

In [9]:
X_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [10]:
X_test

array([[0, 1],
       [6, 7]])

In [11]:
y_train

[1, 4, 2]

In [12]:
y_test

[0, 3]

In [15]:
train_test_split(y, shuffle = False)

[[0, 1, 2], [3, 4]]

# Step 1

In [17]:
from sklearn.datasets import load_iris

In [18]:
iris = load_iris()

In [19]:
X = iris.data

In [20]:
y = iris.target

In [21]:
X.shape

(150, 4)

In [22]:
y.shape

(150,)

# Step 2

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

In [25]:
X_train.shape

(112, 4)

In [28]:
X_test.shape

(38, 4)

In [29]:
print(y_train.shape)
print(y_test.shape)

(112,)
(38,)


# 60% Training 40% Test

In [34]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=4)

# Step 3

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn = KNeighborsClassifier(n_neighbors=3)

In [36]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

# Step 4

In [37]:
y_pred = knn.predict(X_test)

In [38]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [39]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_test, y_pred)

0.9736842105263158

# n_neighbors = 5

In [44]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9736842105263158
